# spring.application.name=guestboard


# spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
# spring.datasource.username=root
# spring.datasource.password=123456
# spring.datasource.url=jdbc:mariadb://localhost:3306/guestboard
# spring.mvc.pathmatch.matching-strategy=ant_path_matcher
# spring.thymeleaf.prefix=classpath:/templates/
# spring.jpa.open-in-view=false
# spring.jpa.hibernate.ddl-auto=create


# properties -> key = value 형태
# yml -> 들여쓰기고 구분되는 계층 구조 & key : value


spring :
  application:
    name: guestboard

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/guestboard
    username: root
    password: 123456

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  thymeleaf:
    prefix: classpath:/templates/

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create

